# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_time_couplegui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# 該gui是使用qtdesigner先設計，再轉為py文件而產生一個大概。 直接Code修改。

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 843)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.button_widget = QtWidgets.QWidget(self.centralwidget)
        self.button_widget.setEnabled(True)
        self.button_widget.setObjectName("button_widget")
        self.Upload_video = QtWidgets.QPushButton(self.button_widget)
        self.Upload_video.setObjectName("Upload_video")
        self.Upload_video2 = QtWidgets.QPushButton(self.button_widget)
        self.Upload_video2.setObjectName("Upload_video2")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.left_one_frame = QtWidgets.QPushButton(self.button_widget)
        self.left_one_frame.setObjectName("left_one_frame")
        self.left_one_frame2 = QtWidgets.QPushButton(self.button_widget)
        self.left_one_frame2.setObjectName("left_one_frame2")
        self.right_one_frame = QtWidgets.QPushButton(self.button_widget)
        self.right_one_frame.setObjectName("right_one_frame")
        self.right_one_frame2 = QtWidgets.QPushButton(self.button_widget)
        self.right_one_frame2.setObjectName("right_one_frame2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.playBtn = QtWidgets.QPushButton(self.button_widget)
        self.playBtn.setObjectName("playBtn")
        self.playBtn2 = QtWidgets.QPushButton(self.button_widget)
        self.playBtn2.setObjectName("playBtn2")

        self.doubleplay = QtWidgets.QPushButton(self.button_widget)
        self.doubleplay.setObjectName("doubleplay")
        self.doubleinverseplay = QtWidgets.QPushButton(self.button_widget)
        self.doubleinverseplay.setObjectName("doubleinverseplay")

        self.main_canvas = QtWidgets.QLabel(self.centralwidget)
        self.main_canvas2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_canvas.sizePolicy().hasHeightForWidth())
        sizePolicy.setHeightForWidth(self.main_canvas2.sizePolicy().hasHeightForWidth())

        self.main_canvas.setSizePolicy(sizePolicy)
        self.main_canvas.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.main_canvas.setAlignment(QtCore.Qt.AlignCenter)
        self.main_canvas.setObjectName("main_canvas")
        self.main_canvas2.setSizePolicy(sizePolicy)
        self.main_canvas2.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.main_canvas2.setAlignment(QtCore.Qt.AlignCenter)
        self.main_canvas2.setObjectName("main_canvas2")

        self.video_progress = QtWidgets.QWidget(self.centralwidget)
        self.video_progress.setObjectName("video_progress")
        self.tl_slider = QtWidgets.QSlider(self.video_progress)
        self.tl_slider.setOrientation(QtCore.Qt.Horizontal)
        self.tl_slider.setObjectName("tl_slider")

        self.video_progress2 = QtWidgets.QWidget(self.centralwidget)
        self.video_progress2.setObjectName("video_progress2")
        self.tl_slider2 = QtWidgets.QSlider(self.video_progress2)
        self.tl_slider2.setOrientation(QtCore.Qt.Horizontal)
        self.tl_slider2.setObjectName("tl_slider2")

        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        spacerItem3 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)

        self.position_label = QtWidgets.QLabel(self.video_progress)
        self.position_label.setObjectName("position_label")

        self.position_label2 = QtWidgets.QLabel(self.video_progress2)
        self.position_label2.setObjectName("position_label2")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 945, 20))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menuWindows = QtWidgets.QMenu(self.menuBar)
        self.menuWindows.setObjectName("menuWindows")
        self.menuExit = QtWidgets.QMenu(self.menuBar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionMivos = QtWidgets.QAction(MainWindow)
        self.actionMivos.setObjectName("actionMivos")
        self.actionMotion_Analysis = QtWidgets.QAction(MainWindow)
        self.actionMotion_Analysis.setObjectName("actionMotion_Analysis")
        self.menuWindows.addAction(self.actionMivos)
        self.menuWindows.addAction(self.actionMotion_Analysis)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menuWindows.menuAction())
        self.menuBar.addAction(self.menuExit.menuAction())

        # 影片上傳與進度按鈕
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.button_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_2.addWidget(self.Upload_video)
        self.horizontalLayout_2.addWidget(self.Upload_video2)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.left_one_frame)
        self.horizontalLayout_2.addWidget(self.right_one_frame)
        self.horizontalLayout_2.addWidget(self.left_one_frame2)
        self.horizontalLayout_2.addWidget(self.right_one_frame2)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.playBtn)
        self.horizontalLayout_2.addWidget(self.playBtn2)

        self.horizontalLayout_2.addWidget(self.doubleplay)
        self.horizontalLayout_2.addWidget(self.doubleinverseplay)

        # 時間條
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.video_progress)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_3.addWidget(self.tl_slider)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_3.addWidget(self.position_label)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.video_progress2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4.addWidget(self.tl_slider2)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_4.addWidget(self.position_label2)


        # 所有物件垂直排列
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.addWidget(self.button_widget)
        self.verticalLayout.addWidget(self.main_canvas)
        self.verticalLayout.addWidget(self.main_canvas2)
        self.verticalLayout.addWidget(self.video_progress)
        self.verticalLayout.addWidget(self.video_progress2)

        # 全畫面伸縮
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_5.addLayout(self.verticalLayout)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Upload_video.setText(_translate("MainWindow", "Upload_Video"))
        self.Upload_video2.setText(_translate("MainWindow", "Upload_Video2"))
        self.left_one_frame.setText(_translate("MainWindow", "Left"))
        self.left_one_frame2.setText(_translate("MainWindow", "Left2"))
        self.right_one_frame.setText(_translate("MainWindow", "Right"))
        self.right_one_frame2.setText(_translate("MainWindow", "Right2"))
        self.playBtn.setText(_translate("MainWindow", "PLAY1"))
        self.playBtn2.setText(_translate("MainWindow", "PLAY2"))
        self.main_canvas.setText(_translate("MainWindow", "indicate video"))
        self.main_canvas2.setText(_translate("MainWindow", "indicate video"))
        self.position_label.setText(_translate("MainWindow", "TextLabel"))
        self.position_label2.setText(_translate("MainWindow", "TextLabel2"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.menuWindows.setTitle(_translate("MainWindow", "Windows"))
        self.menuExit.setTitle(_translate("MainWindow", "Exit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionMivos.setText(_translate("MainWindow", "Mivos"))
        self.actionMotion_Analysis.setText(_translate("MainWindow", "Motion Analysis"))
        self.doubleplay.setText(_translate("MainWindow", "doubleplay"))
        self.doubleinverseplay.setText(_translate("MainWindow", "doubleinverseplay"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
